CREATE TABLE part (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                varchar(60)  NOT NULL, 
    code_norm           varchar(60)  NOT NULL,
    product_group       varchar(180),
    product_group_norm  varchar(180),
    image_file          varchar(300),
    CONSTRAINT uk_part_code      UNIQUE (code),
    CONSTRAINT uk_part_code_norm UNIQUE (code_norm)
);
CREATE INDEX ix_part_group ON part (product_group_norm);

CREATE TABLE vehicle (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(120) NOT NULL,
    name_norm    varchar(120) NOT NULL,
    trim         varchar(180) NOT NULL DEFAULT '',
    trim_norm    varchar(180) NOT NULL DEFAULT '',
    engine_desc  varchar(180) NOT NULL DEFAULT '', 
    engine_cc    integer,          
    CONSTRAINT uk_vehicle_natural UNIQUE (name_norm, trim_norm, engine_desc)
);
CREATE INDEX ix_vehicle_lookup ON vehicle (name_norm, engine_cc);

CREATE TABLE fitment (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id     bigint   NOT NULL,
    vehicle_id  bigint   NOT NULL,
    year_start  smallint NOT NULL,
    year_end    smallint NOT NULL,
    note        varchar(500), 
    CONSTRAINT fk_fitment_part    FOREIGN KEY (part_id)    REFERENCES part (id)    ON DELETE CASCADE,
    CONSTRAINT fk_fitment_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE CASCADE,
    CONSTRAINT uk_fitment UNIQUE (part_id, vehicle_id, year_start, year_end)
);
CREATE INDEX ix_fitment_vehicle_years ON fitment (vehicle_id, year_start, year_end);
CREATE INDEX ix_fitment_part          ON fitment (part_id);

CREATE TABLE specification (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id  bigint       NOT NULL,
    name     varchar(180) NOT NULL,
    value    varchar(300),
    CONSTRAINT fk_specification_part FOREIGN KEY (part_id) REFERENCES part (id) ON DELETE CASCADE,
    CONSTRAINT uk_specification UNIQUE (part_id, name)
);

CREATE TABLE cross_reference (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id              bigint       NOT NULL,
    reference_brand      varchar(120) NOT NULL,
    reference_code       varchar(80)  NOT NULL,
    reference_code_norm  varchar(80)  NOT NULL,
    CONSTRAINT fk_cross_reference_part FOREIGN KEY (part_id) REFERENCES part (id) ON DELETE CASCADE,
    CONSTRAINT uk_cross_reference UNIQUE (part_id, reference_brand, reference_code_norm)
);
CREATE INDEX ix_cross_reference_code ON cross_reference (reference_code_norm);
